server:
 port: 8001
 
spring:
 data:
  mongodb:
   host: localhost
   port: 27017
   database: EkartDB
   
 application:
  name: ORDER-SERVICE

eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url: 
   defaultZone: http://localhost:8761/eureka

 instance:
  prefer-ip-address: true
  
 